on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Satori CI - Automated Testing
        uses: satorici/action@v1.0.0
        env:
          SATORITOKEN: ${{ secrets.SATORITOKEN }}
